name: shoesapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0

  #images
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1

  #Utils
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.5
  auto_size_text: ^3.0.0
  badges: ^3.1.2

  #date
  timeago: ^3.6.1

  #State Management
  flutter_riverpod: ^2.5.1

  #Adaptive
  flutter_platform_widgets: ^6.1.0
  flutter_screenutil: ^5.9.0

  #firebase
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  
  flutter_slidable: ^3.1.0
  

  faker: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

